package com.homeattach.app.ui.theme

import androidx.compose.ui.graphics.Color

// A flat, deliberately terminal-flavoured teal-green/slate palette - not the default Compose
// purple template. Dark is the primary scheme (near-black surfaces so app chrome sits
// comfortably next to the live terminal); light is the secondary scheme. The accent is a
// restrained "terminal green" teal - console character without the neon kitsch.

// Light scheme (secondary)
val md_theme_light_primary = Color(0xFF006B5B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF77F8D6)
val md_theme_light_onPrimaryContainer = Color(0xFF00201A)
val md_theme_light_secondary = Color(0xFF4B635B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE9DD)
val md_theme_light_onSecondaryContainer = Color(0xFF072019)
val md_theme_light_tertiary = Color(0xFF456179)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCBE6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E31)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFBFDF9)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DF)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4945)
val md_theme_light_outline = Color(0xFF6F7975)
val md_theme_light_outlineVariant = Color(0xFFBFC9C3)
val md_theme_light_inverseSurface = Color(0xFF2E3130)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EE)
val md_theme_light_inversePrimary = Color(0xFF56DBBC)
val md_theme_light_surfaceTint = Color(0xFF006B5B)
val md_theme_light_surfaceDim = Color(0xFFDBDED9)
val md_theme_light_surfaceBright = Color(0xFFFBFDF9)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF5F7F3)
val md_theme_light_surfaceContainer = Color(0xFFEFF1ED)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9ECE8)
val md_theme_light_surfaceContainerHighest = Color(0xFFE4E6E2)

// Dark scheme (primary identity) - true-dark friendly: background/surface sit just above
// pure black so the chrome blends with the terminal backdrop on OLED without banding.
val md_theme_dark_primary = Color(0xFF56DBBC)
val md_theme_dark_onPrimary = Color(0xFF00382D)
val md_theme_dark_primaryContainer = Color(0xFF005143)
val md_theme_dark_onPrimaryContainer = Color(0xFF77F8D6)
val md_theme_dark_secondary = Color(0xFFB1CCC2)
val md_theme_dark_onSecondary = Color(0xFF1D352E)
val md_theme_dark_secondaryContainer = Color(0xFF334B44)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE9DD)
val md_theme_dark_tertiary = Color(0xFFADCAE6)
val md_theme_dark_onTertiary = Color(0xFF153349)
val md_theme_dark_tertiaryContainer = Color(0xFF2D4961)
val md_theme_dark_onTertiaryContainer = Color(0xFFCBE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0B0F0E)
val md_theme_dark_onBackground = Color(0xFFDEE4E0)
val md_theme_dark_surface = Color(0xFF0B0F0E)
val md_theme_dark_onSurface = Color(0xFFDEE4E0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4945)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C3)
val md_theme_dark_outline = Color(0xFF89938E)
val md_theme_dark_outlineVariant = Color(0xFF3F4945)
val md_theme_dark_inverseSurface = Color(0xFFDEE4E0)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inversePrimary = Color(0xFF006B5B)
val md_theme_dark_surfaceTint = Color(0xFF56DBBC)
val md_theme_dark_surfaceDim = Color(0xFF0B0F0E)
val md_theme_dark_surfaceBright = Color(0xFF313634)
val md_theme_dark_surfaceContainerLowest = Color(0xFF060A09)
val md_theme_dark_surfaceContainerLow = Color(0xFF131715)
val md_theme_dark_surfaceContainer = Color(0xFF171B19)
val md_theme_dark_surfaceContainerHigh = Color(0xFF212523)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2C302E)

// Terminal surface used behind the live VT100 view - independent of light/dark scheme so
// terminal contents keep a stable, familiar black backdrop either way.
val TerminalBackground = Color(0xFF0B0F0F)
